import json
import sqlite3
import tempfile
import unittest
from contextlib import closing
from datetime import date
from pathlib import Path
from unittest.mock import patch

from sepa_bot.weekly_history import (
    POSTGRES_DDL,
    _normalized_price,
    _parse_number,
    _parse_package,
    _sql_placeholders,
    capturar_precios_semanales,
    crear_esquema,
    obtener_sucursales_seguidas,
    registrar_sin_actualizacion,
    semana_procesada,
)


class WeeklyHistoryTests(unittest.TestCase):
    def setUp(self):
        self.database_mode_patcher = patch(
            "sepa_bot.weekly_history.config.DB_MODE", "sqlite"
        )
        self.database_mode_patcher.start()
        self.addCleanup(self.database_mode_patcher.stop)

    def test_postgres_schema_and_placeholders_use_postgres_syntax(self):
        self.assertNotIn("AUTOINCREMENT", POSTGRES_DDL)
        self.assertIn("GENERATED BY DEFAULT AS IDENTITY", POSTGRES_DDL)

        class RecordingConnection:
            def __init__(self):
                self.statements = []

            def execute(self, statement):
                self.statements.append(statement)

        connection = RecordingConnection()
        with patch("sepa_bot.weekly_history.config.DB_MODE", "postgres"):
            self.assertEqual(
                _sql_placeholders("SELECT * FROM table WHERE key = ?"),
                "SELECT * FROM table WHERE key = %s",
            )
            crear_esquema(connection)

        self.assertEqual(len(connection.statements), 5)
        self.assertIn("GENERATED BY DEFAULT AS IDENTITY", connection.statements[0])

    def test_normalizes_package_price_to_target_unit(self):
        row = {"productos_descripcion": "Leche entera 1 L"}
        package = _parse_package(row, "litro")

        self.assertEqual(package, (1.0, "litro"))
        self.assertEqual(_normalized_price(1500, package, "litro"), 1500)

    def test_parses_argentine_decimal_format(self):
        self.assertEqual(_parse_number("1.250,50"), 1250.5)

    def test_selects_caba_branch_and_keeps_it(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            products = root / "productos.jsonl"
            branches = root / "sucursales.jsonl"
            selection = root / "selection.json"
            _write_jsonl(products, [
                {"id_bandera": "10", "id_comercio": "1", "id_sucursal": "101"},
                {"id_bandera": "10", "id_comercio": "1", "id_sucursal": "102"},
            ])
            _write_jsonl(branches, [
                {"id_comercio": "1", "id_sucursal": "101", "sucursales_localidad": "CABA"},
                {"id_comercio": "1", "id_sucursal": "102", "sucursales_localidad": "La Plata", "sucursales_provincia": "Buenos Aires"},
            ])

            first = obtener_sucursales_seguidas(
                productos_jsonl=products,
                sucursales_jsonl=branches,
                archivo_seleccion=selection,
            )
            second = obtener_sucursales_seguidas(
                productos_jsonl=products,
                sucursales_jsonl=branches,
                archivo_seleccion=selection,
            )

            self.assertEqual(first[0]["id_sucursal"], "101")
            self.assertEqual(first, second)

    def test_weekly_capture_persists_prices_and_is_idempotent(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            products = root / "productos.jsonl"
            branches = root / "sucursales.jsonl"
            selection = root / "selection.json"
            database = root / "sepa.db"
            _write_jsonl(products, [
                {
                    "id_bandera": "10",
                    "id_comercio": "1",
                    "id_sucursal": "101",
                    "id_producto": "500",
                    "ean": "7790001000012",
                    "productos_descripcion": "Azucar Chango comun tipo A 1 kg",
                    "precio_lista": "1.250,50",
                    "precio_referencia": "1.100,00",
                },
                {
                    "id_bandera": "10",
                    "id_comercio": "1",
                    "id_sucursal": "101",
                    "id_producto": "501",
                    "productos_descripcion": "Huevos blancos grandes maple 30 unidades",
                    "precio_lista": "6.000,00",
                    "precio_referencia": "5.700,00",
                },
            ])
            _write_jsonl(branches, [{
                "id_comercio": "1",
                "id_sucursal": "101",
                "sucursales_nombre": "Sucursal Centro",
                "sucursales_localidad": "CABA",
            }])

            result = capturar_precios_semanales(
                database,
                date(2026, 10, 5),
                products,
                branches,
                root / "comercio.jsonl",
                selection,
            )
            self.assertEqual(result["reglas_con_coincidencias"], 2)
            self.assertTrue(semana_procesada(database, date(2026, 10, 5)))

            with closing(sqlite3.connect(database)) as conn:
                row = conn.execute(
                    "SELECT fecha_semana, id_sucursal, precio_lista, precio_lista_normalizado, estado "
                    "FROM historial_canasta_semanal WHERE catalogo_key = 'azucar_chango'"
                ).fetchone()
                eggs = conn.execute(
                    "SELECT cantidad_referencia_mensual, precio_lista_normalizado "
                    "FROM historial_canasta_semanal WHERE catalogo_key = 'huevos_blancos'"
                ).fetchone()

            self.assertEqual(row, ("2026-10-05", "101", 1250.5, 1250.5, "disponible"))
            self.assertEqual(eggs, (30.0, 200.0))

    def test_no_update_marker_prevents_duplicate_week(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            database = Path(temp_dir) / "sepa.db"
            week = date(2026, 10, 5)

            registrar_sin_actualizacion(database, week, "recurso viejo")
            registrar_sin_actualizacion(database, week, "recurso viejo")

            with closing(sqlite3.connect(database)) as conn:
                count = conn.execute("SELECT COUNT(*) FROM capturas_semanales").fetchone()[0]
            self.assertEqual(count, 1)
            self.assertTrue(semana_procesada(database, week))


def _write_jsonl(path: Path, rows: list[dict]) -> None:
    path.write_text("".join(json.dumps(row) + "\n" for row in rows), encoding="utf-8")


if __name__ == "__main__":
    unittest.main()