"""Weekly SEPA basket history in SQLite or PostgreSQL."""

from __future__ import annotations

import json
import logging
import random
import re
import sqlite3
from contextlib import closing
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Any, Iterable

from . import config
from .product_catalog import CATALOG, CatalogItem, encontrar_items, normalizar_texto

logger = logging.getLogger("sepa_bot.weekly_history")

FIELD_ALIASES = {
    "id_bandera": ("id_bandera", "comercio_bandera_id"),
    "id_comercio": ("id_comercio",),
    "id_sucursal": ("id_sucursal",),
    "id_producto": ("id_producto",),
    "ean": ("ean", "productos_ean"),
    "descripcion": ("productos_descripcion", "descripcion", "producto_descripcion", "nombre_producto"),
    "marca": ("productos_marca", "marca"),
    "precio_lista": ("productos_precio_lista", "precio_lista"),
    "precio_referencia": ("productos_precio_referencia", "precio_referencia"),
    "nombre_sucursal": ("sucursales_nombre", "nombre_sucursal", "nombre"),
    "localidad": ("sucursales_localidad", "localidad", "sucursal_localidad"),
    "provincia": ("sucursales_provincia", "provincia"),
    "cantidad_presentacion": (
        "productos_cantidad_presentacion", "cantidad_presentacion", "contenido_neto",
        "productos_contenido", "contenido",
    ),
    "unidad_presentacion": (
        "productos_unidad_medida", "unidad_medida", "productos_unidad_venta",
        "unidad_venta", "unidad",
    ),
}

DDL = """
CREATE TABLE IF NOT EXISTS historial_canasta_semanal (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    fecha_semana TEXT NOT NULL,
    fecha_consulta TEXT NOT NULL,
    id_bandera TEXT NOT NULL,
    cadena TEXT NOT NULL,
    id_comercio TEXT NOT NULL,
    id_sucursal TEXT NOT NULL,
    sucursal TEXT,
    localidad TEXT,
    categoria TEXT NOT NULL,
    catalogo_key TEXT NOT NULL,
    opcion INTEGER,
    producto_catalogo TEXT NOT NULL,
    id_producto TEXT NOT NULL,
    ean TEXT,
    descripcion TEXT,
    marca TEXT,
    presentacion TEXT,
    cantidad_envase REAL,
    unidad_envase TEXT,
    precio_lista REAL,
    precio_referencia REAL,
    precio_lista_normalizado REAL,
    precio_referencia_normalizado REAL,
    unidad_normalizada TEXT NOT NULL,
    cantidad_referencia_mensual REAL,
    estado TEXT NOT NULL,
    UNIQUE (fecha_semana, id_bandera, id_comercio, id_sucursal, catalogo_key, id_producto)
);

CREATE TABLE IF NOT EXISTS capturas_semanales (
    fecha_semana TEXT PRIMARY KEY,
    fecha_consulta TEXT NOT NULL,
    estado TEXT NOT NULL,
    detalle TEXT
);

CREATE INDEX IF NOT EXISTS idx_historial_canasta_fecha
    ON historial_canasta_semanal(fecha_semana);
CREATE INDEX IF NOT EXISTS idx_historial_canasta_producto
    ON historial_canasta_semanal(catalogo_key, fecha_semana);
CREATE INDEX IF NOT EXISTS idx_historial_canasta_cadena
    ON historial_canasta_semanal(id_bandera, fecha_semana);
"""

POSTGRES_DDL = DDL.replace(
    "INTEGER PRIMARY KEY AUTOINCREMENT",
    "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
)


def _connect(db_path: Path):
    if config.DB_MODE == "postgres":
        if not config.DATABASE_URL:
            raise RuntimeError("DB_MODE=postgres requiere configurar DATABASE_URL.")
        import psycopg

        return psycopg.connect(config.DATABASE_URL)
    return sqlite3.connect(db_path)


def crear_esquema(conn) -> None:
    """Create the weekly-history tables for the configured database engine."""
    if config.DB_MODE == "postgres":
        for statement in POSTGRES_DDL.split(";"):
            if statement.strip():
                conn.execute(statement)
    else:
        conn.executescript(DDL)


def _sql_placeholders(statement: str) -> str:
    return statement.replace("?", "%s") if config.DB_MODE == "postgres" else statement


def _value(row: dict[str, Any], key: str, default: Any = "") -> Any:
    for field in FIELD_ALIASES.get(key, (key,)):
        value = row.get(field)
        if value not in (None, ""):
            return value
    return default


def _jsonl_rows(path: Path) -> Iterable[dict[str, Any]]:
    if not path.exists():
        return
    with path.open("r", encoding="utf-8") as source:
        for line in source:
            if line.strip():
                yield json.loads(line)


def _branch_key(row: dict[str, Any]) -> tuple[str, str]:
    return str(_value(row, "id_comercio")), str(_value(row, "id_sucursal"))


def _chain_key(row: dict[str, Any]) -> str:
    return str(_value(row, "id_bandera") or _value(row, "id_comercio"))


def _area_priority(branch: dict[str, Any]) -> int:
    place = normalizar_texto(
        f"{_value(branch, 'localidad')} {_value(branch, 'provincia')}"
    )
    if any(term in place for term in ("CABA", "CAPITAL FEDERAL", "CIUDAD AUTONOMA")):
        return 0
    if "BUENOS AIRES" in place or "GRAN BUENOS AIRES" in place:
        return 1
    return 2


def obtener_sucursales_seguidas(
    productos_jsonl: Path | None = None,
    sucursales_jsonl: Path | None = None,
    comercios_jsonl: Path | None = None,
    archivo_seleccion: Path | None = None,
) -> list[dict[str, str]]:
    """Keep one stable branch for every SEPA banner, preferring CABA then GBA."""
    productos_jsonl = productos_jsonl or config.JSON_DIR / "productos.jsonl"
    sucursales_jsonl = sucursales_jsonl or config.JSON_DIR / "sucursales.jsonl"
    comercios_jsonl = comercios_jsonl or config.JSON_DIR / "comercio.jsonl"
    archivo_seleccion = archivo_seleccion or config.HISTORIAL_SUCURSALES_ARCHIVO

    chain_names: dict[str, str] = {}
    for row in _jsonl_rows(comercios_jsonl):
        name = str(
            _value(row, "comercio_bandera_nombre")
            or _value(row, "comercio_razon_social")
            or _value(row, "nombre_comercio")
        )
        for key in ("id_bandera", "comercio_bandera_id", "id_comercio"):
            if row.get(key) and name:
                chain_names[str(row[key])] = name

    branch_details = {
        _branch_key(row): row for row in _jsonl_rows(sucursales_jsonl)
        if _branch_key(row) != ("", "")
    }
    candidates: dict[str, dict[tuple[str, str], dict[str, str]]] = {}
    for row in _jsonl_rows(productos_jsonl):
        chain_id = _chain_key(row)
        branch_key = _branch_key(row)
        if not chain_id or branch_key == ("", ""):
            continue
        details = branch_details.get(branch_key, {})
        chain_name = str(
            _value(row, "comercio_bandera_nombre")
            or _value(row, "nombre_comercio")
            or chain_names.get(chain_id)
            or chain_names.get(branch_key[0])
            or chain_id
        )
        candidates.setdefault(chain_id, {})[branch_key] = {
            "id_bandera": chain_id,
            "cadena": chain_name,
            "id_comercio": branch_key[0],
            "id_sucursal": branch_key[1],
            "sucursal": str(_value(details, "nombre_sucursal")),
            "localidad": str(_value(details, "localidad")),
        }

    previous = []
    if archivo_seleccion.exists():
        try:
            previous = json.loads(archivo_seleccion.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            logger.warning("No se pudo leer la selección guardada de sucursales: %s", exc)

    previous_by_chain: dict[str, dict[str, Any]] = {}
    for entry in previous:
        chain_id = str(entry.get("id_bandera") or entry.get("id_comercio") or "")
        if chain_id:
            previous_by_chain[chain_id] = entry

    selected: list[dict[str, str]] = []
    for chain_id, chain_candidates in sorted(candidates.items()):
        old = previous_by_chain.get(chain_id)
        old_key = (str((old or {}).get("id_comercio", "")), str((old or {}).get("id_sucursal", "")))
        if old_key in chain_candidates:
            selected.append(chain_candidates[old_key])
            continue

        best_priority = min(_area_priority(branch) for branch in chain_candidates.values())
        area_candidates = [
            branch for branch in chain_candidates.values()
            if _area_priority(branch) == best_priority
        ]
        selected.append(random.choice(area_candidates))

    archivo_seleccion.parent.mkdir(parents=True, exist_ok=True)
    archivo_seleccion.write_text(
        json.dumps(selected, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    logger.info("Sucursales seguidas: %d cadenas", len(selected))
    return selected


def _parse_number(value: Any) -> float | None:
    text = str(value or "").strip().replace("$", "").replace(" ", "")
    if not text:
        return None
    if "," in text and "." in text:
        if text.rfind(",") > text.rfind("."):
            text = text.replace(".", "").replace(",", ".")
        else:
            text = text.replace(",", "")
    elif "," in text:
        text = text.replace(".", "").replace(",", ".")
    try:
        return float(text)
    except ValueError:
        return None


def _parse_package(row: dict[str, Any], target_unit: str) -> tuple[float | None, str | None]:
    fields = (
        "productos_presentacion", "presentacion", "contenido", "contenido_neto",
        "productos_contenido", "productos_cantidad_presentacion", "productos_unidad_medida",
        "cantidad_presentacion", "unidad_medida", "productos_unidad_venta", "unidad_venta", "unidad",
        "productos_descripcion", "descripcion", "producto_descripcion", "nombre_producto",
    )
    text = normalizar_texto(" ".join(str(row.get(field) or "") for field in fields))
    text = text.replace(",", ".")
    units = r"KG|KGS|KILO(?:S)?|G|GR|GRAMO(?:S)?|L|LT|LTS|LITRO(?:S)?|ML|CC|UNIDADES?|U|DOCENA(?:S)?|MAPLE"
    multipack = re.search(rf"(\d+(?:\.\d+)?)\s*[X×]\s*(\d+(?:\.\d+)?)\s*({units})\b", text)
    single = re.search(rf"(\d+(?:\.\d+)?)\s*({units})\b", text)

    if multipack:
        quantity = float(multipack.group(1)) * float(multipack.group(2))
        unit = multipack.group(3)
    elif single:
        quantity = float(single.group(1))
        unit = single.group(2)
    else:
        unit_only = re.search(rf"\b({units})\b", text)
        if unit_only:
            quantity, unit = 1.0, unit_only.group(1)
        elif "GRANEL" in text:
            quantity, unit = 1.0, target_unit.upper()
        else:
            return None, None

    if unit in {"G", "GR", "GRAMO", "GRAMOS"}:
        return quantity / 1000, "kg"
    if unit in {"KG", "KGS", "KILO", "KILOS"}:
        return quantity, "kg"
    if unit in {"ML", "CC"}:
        return quantity / 1000, "litro"
    if unit in {"L", "LT", "LTS", "LITRO", "LITROS"}:
        return quantity, "litro"
    if unit in {"DOCENA", "DOCENAS"}:
        return quantity * 12, "unidad"
    if unit == "MAPLE":
        return quantity * 30, "unidad"
    if unit in {"UNIDAD", "UNIDADES", "U"}:
        return quantity, "unidad"
    return quantity, target_unit


def _normalized_price(price: float | None, package: tuple[float | None, str | None], target_unit: str) -> float | None:
    quantity, unit = package
    if price is None or quantity is None or unit != target_unit or quantity <= 0:
        return None
    return price / quantity


def _product_fields(row: dict[str, Any]) -> tuple[str, str, str, str]:
    return (
        str(_value(row, "id_producto")),
        str(_value(row, "ean")),
        str(_value(row, "descripcion")),
        str(_value(row, "marca")),
    )


def _candidate_tuple(
    week_date: date,
    queried_at: str,
    store: dict[str, str],
    item: CatalogItem,
    row: dict[str, Any],
) -> tuple[Any, ...]:
    product_id, ean, description, brand = _product_fields(row)
    package = _parse_package(row, item.unit)
    price_list = _parse_number(_value(row, "precio_lista", None))
    price_reference = _parse_number(_value(row, "precio_referencia", None))
    package_description = " ".join(
        str(row.get(field) or "")
        for field in (
            "productos_presentacion", "presentacion", "contenido", "contenido_neto",
            "productos_contenido", "productos_cantidad_presentacion", "productos_unidad_medida",
            "cantidad_presentacion", "unidad_medida", "productos_unidad_venta", "unidad_venta", "unidad",
        )
    ).strip()
    quantity, package_unit = package
    return (
        week_date.isoformat(), queried_at, store["id_bandera"], store["cadena"],
        store["id_comercio"], store["id_sucursal"], store["sucursal"], store["localidad"],
        item.category, item.key, item.option, item.label, product_id or ean or "", ean,
        description, brand, package_description, quantity, package_unit, price_list,
        price_reference, _normalized_price(price_list, package, item.unit),
        _normalized_price(price_reference, package, item.unit), item.unit,
        item.monthly_quantity,
        "disponible" if price_list is not None or price_reference is not None else "sin_precio",
    )


def semana_procesada(db_path: Path, week_date: date) -> bool:
    if config.DB_MODE == "sqlite" and not db_path.exists():
        return False
    with closing(_connect(db_path)) as conn:
        crear_esquema(conn)
        result = conn.execute(
            _sql_placeholders(
                "SELECT 1 FROM capturas_semanales WHERE fecha_semana = ?"
            ),
            (week_date.isoformat(),),
        ).fetchone()
        conn.commit()
    return result is not None


def registrar_sin_actualizacion(db_path: Path, week_date: date, detail: str) -> dict[str, Any]:
    queried_at = datetime.now(timezone.utc).isoformat()
    db_path.parent.mkdir(parents=True, exist_ok=True)
    with closing(_connect(db_path)) as conn:
        crear_esquema(conn)
        conn.execute(
            _sql_placeholders(
                "INSERT INTO capturas_semanales VALUES (?, ?, ?, ?) "
                "ON CONFLICT (fecha_semana) DO NOTHING"
            ),
            (week_date.isoformat(), queried_at, "sin_actualizacion", detail),
        )
        conn.commit()
    logger.info("Sin actualización del recurso semanal para %s: %s", week_date, detail)
    return {"fecha_semana": week_date.isoformat(), "estado": "sin_actualizacion", "detalle": detail}


def capturar_precios_semanales(
    db_path: Path,
    week_date: date,
    productos_jsonl: Path,
    sucursales_jsonl: Path,
    comercios_jsonl: Path,
    archivo_seleccion: Path,
) -> dict[str, Any]:
    queried_at = datetime.now(timezone.utc).isoformat()
    selected = obtener_sucursales_seguidas(
        productos_jsonl=productos_jsonl,
        sucursales_jsonl=sucursales_jsonl,
        comercios_jsonl=comercios_jsonl,
        archivo_seleccion=archivo_seleccion,
    )
    if not selected:
        raise RuntimeError("No se encontraron sucursales SEPA elegibles para capturar precios.")

    selection_by_branch = {
        (store["id_bandera"], store["id_comercio"], store["id_sucursal"]): store
        for store in selected
    }
    matches: dict[tuple[str, str, str, str], list[tuple[CatalogItem, dict[str, Any]]]] = {}

    for row in _jsonl_rows(productos_jsonl):
        store_key = (
            _chain_key(row), str(_value(row, "id_comercio")), str(_value(row, "id_sucursal"))
        )
        if store_key not in selection_by_branch:
            continue
        for item in encontrar_items(row):
            matches.setdefault(store_key + (item.key,), []).append((item, row))

    insert_sql = """
        INSERT INTO historial_canasta_semanal (
            fecha_semana, fecha_consulta, id_bandera, cadena, id_comercio, id_sucursal,
            sucursal, localidad, categoria, catalogo_key, opcion, producto_catalogo,
            id_producto, ean, descripcion, marca, presentacion, cantidad_envase,
            unidad_envase, precio_lista, precio_referencia, precio_lista_normalizado,
            precio_referencia_normalizado, unidad_normalizada,
            cantidad_referencia_mensual, estado
        ) VALUES ({placeholders})
        ON CONFLICT (fecha_semana, id_bandera, id_comercio, id_sucursal, catalogo_key, id_producto)
        DO UPDATE SET
            fecha_consulta=excluded.fecha_consulta,
            precio_lista=excluded.precio_lista,
            precio_referencia=excluded.precio_referencia,
            precio_lista_normalizado=excluded.precio_lista_normalizado,
            precio_referencia_normalizado=excluded.precio_referencia_normalizado,
            estado=excluded.estado
    """
    placeholders = ", ".join(
        ["%s" if config.DB_MODE == "postgres" else "?"] * 26
    )
    insert_sql = insert_sql.format(placeholders=placeholders)

    rows_to_insert: list[tuple[Any, ...]] = []
    matched_keys: set[tuple[str, str, str, str]] = set()
    for store_key, store in selection_by_branch.items():
        for item in CATALOG:
            match_key = store_key + (item.key,)
            candidates = matches.get(match_key, [])
            if candidates:
                matched_keys.add(match_key)
                for matched_item, row in candidates:
                    rows_to_insert.append(
                        _candidate_tuple(week_date, queried_at, store, matched_item, row)
                    )
            else:
                rows_to_insert.append((
                    week_date.isoformat(), queried_at, store["id_bandera"], store["cadena"],
                    store["id_comercio"], store["id_sucursal"], store["sucursal"], store["localidad"],
                    item.category, item.key, item.option, item.label, "", None, None, None,
                    None, None, None, None, None, None, None, item.unit,
                    item.monthly_quantity, "sin_dato",
                ))

    db_path.parent.mkdir(parents=True, exist_ok=True)
    with closing(_connect(db_path)) as conn:
        crear_esquema(conn)
        conn.executemany(insert_sql, rows_to_insert)
        conn.execute(
            _sql_placeholders(
                "INSERT INTO capturas_semanales VALUES (?, ?, ?, ?) "
                "ON CONFLICT (fecha_semana) DO NOTHING"
            ),
            (
                week_date.isoformat(), queried_at,
                "completada" if matched_keys else "completada_sin_coincidencias",
                f"{len(matched_keys)} reglas de producto con coincidencias; {len(selected)} sucursales",
            ),
        )
        conn.commit()

    status_counts: dict[str, int] = {}
    for row in rows_to_insert:
        status = str(row[-1])
        status_counts[status] = status_counts.get(status, 0) + 1
    return {
        "fecha_semana": week_date.isoformat(),
        "sucursales": len(selected),
        "filas_historial": len(rows_to_insert),
        "reglas_con_coincidencias": len(matched_keys),
        "estados": status_counts,
        "db_mode": config.DB_MODE,
        **({"db_path": str(db_path)} if config.DB_MODE == "sqlite" else {}),
    }